name: judiciary_platform
description: AI-Enhanced Judiciary Platform - Flutter Frontend

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  
  # HTTP Client
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  
  # UI Components
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  
  # Charts
  fl_chart: ^0.64.0
  
  # Navigation
  go_router: ^12.1.1
  
  # Forms & Validation
  formz: ^0.6.1
  
  # Utils
  intl: ^0.18.1
  url_launcher: ^6.2.1
  webview_flutter: ^4.4.2
  
  # Image handling
  image_picker: ^1.0.4
  
  # File handling
  file_picker: ^6.1.1
  
  # Permissions
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code generation
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  
  # Linting
  flutter_lints: ^3.0.0
  
  # Testing
  bloc_test: ^9.1.5
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  
  # assets:
    # - assets/images/
    # - assets/icons/
    # - assets/fonts/
  
  # fonts:
    # - family: Roboto
      # fonts:
        # - asset: assets/fonts/Roboto-Regular.ttf
        # - asset: assets/fonts/Roboto-Bold.ttf
          # weight: 700